#!/usr/bin/env node
let process=require("process");
let child_process=require("child_process");
const { ESLint } = require("eslint");

function exec(name){
    return new Promise((res)=>{
        child_process.exec(name, res);
    });
}
(async function main() {
  // 1. Create an instance with the `fix` option.
  const eslint = new ESLint({ fix: false });

  // 2. Lint files. This doesn't modify target files.
  await exec("git status push -k");
  const results = await eslint.lintFiles(["index.js"]);
  await exec("git status pop");
  // 4. Format the results.
  const formatter = await eslint.loadFormatter("stylish");
  const resultText = formatter.format(results);

  // 5. Output it.
  console.log(resultText);

  for (let res of results) {
      if(res.errorCount){
          process.exitCode=1;
      }
  }
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});